scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 5s

    static_configs:
      - targets: ['192.168.33.10:9090']

  - job_name: backend
    metrics_path: 'kaddem/actuator/prometheus'
    static_configs:
      - targets: ['192.168.33.10:9009']